# Navigation Links
#   Anchor links (#id) match the `id:` field of sections in content/_index.md.
#   The weight parameter defines the order that links appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Papers
    url: /#papers
    weight: 11
  - name: News
    url: /#news
    weight: 12
  - name: Certifications
    url: /#certifications
    weight: 13
  - name: Experience
    url: experience/
    weight: 20
  - name: Publications
    url: publication/
    weight: 30
